### ISSUE TITLE
Is it possible to provide the download for Losungen 2022?

### ISSUE THREAD

**Issue by tigexplorer** [schalterDev/Losungen-Android-2#67]
I love this app!
It seems, that the update for 2022 is not available?
Is there a way to use this app with Losungen 2022?

Thanx for your wok!

**Comment by schalterDev** [comment]
English answer below
### Deutsche Antwort:
Leider habe ich die App eingestellt. Das hat zwei Gründe:

1. Von den Herausgebern der Losungen ist meine App nicht gewünscht
2. Meine Zeit zum Pflegen und Warten der App ist im Moment zu knapp.

**Es gibt Alternativen**

Es gibt eine offizielle App der Losungen mit ähnlichen Funktionen: https://play.google.com/store/apps/details?id=de.marungbaehr.dielosungen
Es können die Losungen jeden Tag auf dem Handy angeschaut werden.

Die Andachten wurden von ERF bereitgestellt.
Wenn die Andachten weiter angehört werde möchten kann man das auch direkt von der Seite vom ERF: https://www.erf.de/hoeren-sehen/erf-plus/audiothek/wort-zum-tag/73

**Ein weiterer Hinweis**

Ich arbeite gerade als Entwickler in einem anderen christlichen Projekt mit. Wenn Dir die App gefallen hat, wird dir das Projekt auch gefallen und weiterhelfen:
Das Projekt heißt **CROSSLOAD**: https://crossload.org
Das ist eine Internetseite mit vielen guten Predigten und anderem Material. Wenn man eine Andacht / Predigt vorbereiten muss oder Antworten auf Fragen sucht wird man hier schnell fündig. Würde mich freuen wenn Du mal vorbei schaust. Wenn du CROSSLOAD gut findest kannst du dafür auch gerne Werbung in deiner Gemeinde oder bei deinen Freunden machen.

### English Answer:
Unfortunately, I have discontinued the app. This has two reasons:

1. my app is not wanted by the publishers of the "losungen".
2. my time to maintain the app is too short at the moment.

**There are alternatives**

There is an official app of the Losungen with similar functions (only in german): https://play.google.com/store/apps/details?id=de.marungbaehr.dielosungen.
It can be used to view the "losungen" every day on your phone.

The german devotions are provided by ERF.
If you want to continue listening to the devotions, you can do so directly from the ERF website: https://www.erf.de/hoeren-sehen/erf-plus/audiothek/wort-zum-tag/73

**Another hint**

I am currently working as a developer in another christian project (again only in german). If you like the app, you will also like the project and it will help you:
The project is called CROSSLOAD: https://crossload.org
This is a website with many good sermons and other material. If you have to prepare a devotion / sermon or xou are looking for answers to questions, you will quickly find what you are looking for. I would be happy if you look. If you like CROSSLOAD you can share it in your church or with your friends.

**Comment by schalterDev** [comment]
It would be possible to provide an text field to paste the url of the xml-File of Losungen: https://www.losungen.de/digital/
But to provide an update in the play store the Target SDK must be updated. There are also a lot of bugs in the app with the notifications, widget and the devotion from ERF. If anyone likes to fix this I would publish an update to the play store

**Comment by tigexplorer** [comment]
Is such an entry field for a xml file url fixing the license problem?
If so, it would be nice, if someone can add this.

And even better as to update the app in the play store, it could make available in the F-Droid Store!?

**Comment by DerVogel2020** [comment]
Im Prinzip müssten nur die letzten Commits für die 2021-Anpassung an 2022 adaptiert werden. Das Könnte ich  die nächsten Tage mal machen.
@schalterDev reicht das, oder ist das SDK Update zwingend erforderlich um ein Update in den Play Store laden zu können?

**Comment by schalterDev** [comment]
Target SDK muss mindestens Version 30 sein (im Moment 28), um ein Update zu veröffentlichen (https://support.google.com/googleplay/android-developer/answer/9859152?visit_id=637770122037447652-3476790983&rd=1#targetsdk&zippy=%2Ctarget-api-level-requirements-for-play-console).

Die Daten für 2022 können aber auch ohne ein Update zur Verfügung gestellt werden, das habe ich gerade gemacht: https://github.com/schalterDev/Losungen-Android-2/commit/c3d2a9b6f391d906795167ee5d231de5a97a782f
Die Wochen- und Monatsverse sind aber nicht dabei, weil ich die selbst aufbereitet habe. Ich habe im Moment leider auch kein Gerät das zu testen, sollte aber funktionieren

**Comment by DerVogel2020** [comment]
Ja danke. Funktioniert prima.
Aber müssten die Nutzungsbedingungen jetzt nicht auf https://www.losungen.de/fileadmin/media-losungen/download/NUTZUNGSBEDINGUNGEN_November_2021.pdf verweisen?

Das Format für die Monats- und Wochensprüche schau ich mir die Tage mal an.

**Comment by pilian** [comment]
Vielen Dank für die Losungen 2022. Die habe ich schon sehr vermisst.
Ich finde diese App viel sympathischer als die von Reinhardt GmbH.
Eine Veröffentlichung auf F-Droid würde ich begrüßen. Würde damit das Target SDK Problem entfallen?

**Comment by schalterDev** [comment]
> Vielen Dank für die Losungen 2022. Die habe ich schon sehr vermisst. Ich finde diese App viel sympathischer als die von Reinhardt GmbH. Eine Veröffentlichung auf F-Droid würde ich begrüßen. Würde damit das Target SDK Problem entfallen?

Ja ich glaube das Target SDK Problem entfällt. Die App verwendet aber die Google Play Services als Abhängigkeit, das ist bei F-Droid nicht gewollt. Diese müsste man entfernen, dann wäre es kein Problem
